COMMENT = _{ "#" ~ commentchar* }
commentchar = _{ !NEWLINE ~ ANY }
whitespace = _{ " " | "\t" | NEWLINE }
wordchar = _{ !(whitespace | "#" | "=" | "{" | "}" | "\"") ~ ANY }
word = _{ (wordchar+) | ("\"" ~ whitespace* ~ (wordchar+ ~ whitespace*)+ ~ "\"") }
key = { word }
value = { word | list }
pair = { key ~ whitespace* ~ "=" ~ whitespace* ~ value }
list = { "{" ~ whitespace* ~ ((pair | word) ~ whitespace*)* ~ "}" }
file = { SOI ~ whitespace* ~ (pair ~ whitespace*)* ~ EOI }
